### PR TITLE
Swift Package manager, Linux support

### PR DESCRIPTION
**Pull request by michael-yuji**

### CODE REVIEW

**Comment by 1024jp** [comment]
thanks,
I'll review your pr when I have time (sorry but I'm now quite busy.

**Comment by michael-yuji** [comment]
No problem. I added some more fix (NSLocalizedString not available on Linux) and some instructions in the readme file as well.

**Comment by zarghol** [comment]
@1024jp  It's been more than a month now, can you merge it now please, it could be useful for users of SPM in the server :)

**Comment by 1024jp** [comment]
Sorry for my late. I've just merged the p-r (without test).
Please tell me if it doesn't work.

**Comment by zarghol** [comment]
Thanks ! to use this repo in SPM, we need a release with a version to show, like 3.0.2 or 3.1 or whatever

**Comment by 1024jp** [comment]
@zarghol I see. I'll do it just now.

**Comment by 1024jp** [comment]
I've tagged it as 3.1.0.

**Comment by zarghol** [comment]
Thank ! I can get in my project ! 👍

**Comment by zarghol** [comment]
well it half works, because of tests :
`swift-package: error: the package has an unsupported layout, unexpected source file(s) found: XXX/Packages/GzipSwift-3.1.0/Tests/GzipTests.swift
fix: move the file(s) inside a module
`
in the Package.swift of the project, you can exclude directory to not include in spm 

> let package = Package(
>    name: "MyProject",
>    dependencies: [
>        .Package(url: "https://github.com/vapor/vapor.git", majorVersion: 1, minor: 1),
>		.Package(url: "https://github.com/vapor/sqlite-provider.git", majorVersion: 1, minor: 1),
>        .Package(url: "https://github.com/1024jp/GzipSwift", versions: Version(0,0,0)..<Version(5,0,0))
>    ],
>    exclude: [
>        "Config",
>        "Database",
>        "Localization",
>        "Public",
>        "Resources",
>        "Tests",
>    ])

So can you add Tests to exclude ? or do you want a PR just for this ?

**Comment by 1024jp** [comment]
I forgot to mention it. I also changed package name (framework name?) from GzipSwift to Gzip.

**Comment by zarghol** [comment]
ok I'll test it

**Comment by zarghol** [comment]
well, your changes isn't part of a Release, so I can't retrieve it

**Comment by 1024jp** [comment]
So you mean I need another tag like 3.1.1?

**Comment by zarghol** [comment]
yes, because your last modification isn't in the 3.1
SPM check version via git tags, so if I want a package in a version A, I need a tag A. 
if I specify a Version Range like `Version(0,0,0)..<Version(5,0,0)`, SPM will check the last version in the range and if there is no version with your modification, I can't get it

**Comment by 1024jp** [comment]
Ok, then, I've updated to 3.1.1.

**Comment by zarghol** [comment]
Thank you, I'll re-test soon

**Pull request merged**
